name: "Reuseable Template Sync"

on:
  workflow_call:
    inputs:
      mappings:
        required: true
        type: "string"
        description: "Space-separated list of source:target (e.g.,
          gitignore/js.gitignore:.gitignore)"
      commit_msg_template:
        required: false
        type: "string"
        default: "sync `{dest}` from `{src}`"
        description: "A template for the commit message. replaces {src} and {dest}."
    secrets:
      APP_PRIVATE_KEY:
        required: false
        description: "Private key of app 3692187."

jobs:
  sync:
    runs-on: "ubuntu-latest"
    env:
      BASE_REPO: "Mephisto5558/Mephisto5558"
      BASE_BRANCH: "main"

      APP_ID: 3692187
      APP_NAME: "mephisto5558-template-sync"

      MAPPINGS: "${{ inputs.mappings }}"
      COMMIT_MSG_TEMPLATE: "${{ inputs.commit_msg_template }}"
      START_MARKER: "=== CUSTOM START ==="
      END_MARKER: "=== CUSTOM END ==="

    steps:
      - name: "Generate Token"
        id: "generate_token"
        uses: "actions/create-github-app-token@v3"
        with:
          client-id: "${{ env.APP_ID }}"
          private-key: "${{ secrets.APP_PRIVATE_KEY }}"

      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
          token: "${{ steps.generate_token.outputs.token }}"
          persist-credentials: false

      - name: "Fetch and run sync script"
        id: "sync"
        run: |
          SCRIPT_URL="https://raw.githubusercontent.com/$BASE_REPO/$BASE_BRANCH/.github/scripts/template-sync.sh"
          curl -sSf "$SCRIPT_URL" -o template-sync.sh
          chmod +x template-sync.sh

          ./template-sync.sh
          rm template-sync.sh

      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v8"
        with:
          title: "Sync templates from Upstream"
          commit-message: "sync templates from ${{ env.BASE_REPO }}"
          body: |
            Sync templates from the [base repo](https://github.com/${{ env.BASE_REPO }}/tree/${{ env.BASE_BRANCH }}/templates).

            ## Changelog
            ${{ env.CHANGELOG }}

          base: "${{ env.BASE_BRANCH }}"
          branch: "sync-templates"
          delete-branch: true

          token: ${{ steps.generate_token.outputs.token }}
          sign-commits: true

          reviewers: "Mephisto5558"